### PR TITLE
#62 docs have wrong snapshot version

### PR DESCRIPTION
**Pull request by maurezen**
Fixed the version in docs.

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, I'll ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@carlosmiranda please review this PR

**Comment by carlosmiranda** [comment]
@rultor Try to merge please

**Comment by dmarkov** [comment]
@carlosmiranda paid, thanks, added **16 mins** to your account, payment `50565681`... +16 added to your rating, at the moment it is: [+1649](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
