### PR TITLE
Fix JsonResponse site example

### PR DESCRIPTION
**Pull request by marcel-dias**
This PR will fix the JsonResponse site example template.

### CODE REVIEW

**Comment by dmarkov** [comment]
@marceldiass Many thanks, I will find someone to review it before we merge

**Comment by dmarkov** [comment]
@yegor256 the PR is rather short, please review it

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor mereg

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#144` is not assigned, can't get performer

**Pull request closed without merging**
