### PR TITLE
Implement JacksonResponse

### PR DESCRIPTION
**Pull request by chmodas**

### CODE REVIEW

**Comment by dmarkov** [comment]
@chmodas Many thanks for the PR, let me find a reviewer for it

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@chmodas thanks!

**Comment by chmodas** [comment]
@yegor256 , thank you for the wonderful library :)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
