### PR TITLE
For #171: Bump parent to jcabi 1.25.1

### PR DESCRIPTION
**Pull request by andreoss**
This is for #171 

- Bump parent to 1.25.1 (openjdk8)
- Perform qulice penance
- Replace cobertura with jacoco
- Explicitly set dependencies of `jcabi-matchers` in order to avoid conflicts

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by andreoss** [comment]
@yegor256 CI buils appears to be "pending", but in fact it has been completed successfully, not sure what is the problem here.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#193](https://github.com/jcabi/jcabi-http/issues/193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#193` is not assigned, can't get performer

**Pull request merged**
