### PR TITLE
Fix an issue with trailing ampersand

### PR DESCRIPTION
**Pull request by alxn**
I've noticed that a single `.formParam()` also appending a `&` for the next parameter, it should really be prepending from the second parameter.

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor looks good, merge it pls

**Comment by dmarkov** [comment]
@alxn Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@pinaf please review, thanks

**Comment by pinaf** [comment]
@alxn do you mind taking a look at the failing tests?

**Comment by alxn** [comment]
@pinaf sure.

**Comment by alxn** [comment]
@pinaf I see these two fail on master:
```
Tests in error: 
  RequestITCase.sendsHttpRequestAndProcessesHttpResponse:84 » IllegalArgument In...
  RequestITCase.sendsHttpRequestAndProcessesHttpResponse:84 » IllegalArgument In...
```

Don't see `processesNotOkHttpResponse` fail on my branch...?

**Comment by pinaf** [comment]
@yegor256 is there a problem with master?

**Comment by pinaf** [comment]
@alxn same here. When building master I get:
```
Tests in error: 
  RequestITCase.sendsHttpRequestAndProcessesHttpResponse:84 » IllegalArgument In...
  RequestITCase.sendsHttpRequestAndProcessesHttpResponse:84 » IllegalArgument In...
```

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by pinaf** [comment]
@alxn checkstyle now

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by yegor256** [comment]
@alxn thanks!

**Comment by dmarkov** [comment]
@pinaf Thanks a lot, I just topped your account for **19 mins**, transaction ID `AP-5CK65052WL570310F`, total time was 70 hours and 5 mins... review comments (c=4) added as a bonus... +19 added to your rating, at the moment it is: [+4812](http://www.netbout.com/b/35128?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
