### PR TITLE
For #195: Move to Junit 5

### PR DESCRIPTION
**Pull request by andreoss**
This is for #195 
- Partial migration to Junit 5 by regex

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by andreoss** [comment]
@0crat merge

**Comment by andreoss** [comment]
@rultor merge

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/jcabi/jcabi-http/issues/198#issuecomment-655048202); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#198](https://github.com/jcabi/jcabi-http/issues/198); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by andreoss** [comment]
@rultor merge

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/jcabi/jcabi-http/issues/198#issuecomment-655054330); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by andreoss** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#198` is not assigned, can't get performer

**Pull request merged**
