### PR TITLE
Fix for issue #85 RequestBody.BaseBody.formParam append extra & at th…

### PR DESCRIPTION
**Pull request by YamStranger**
Fix for issue RequestBody.BaseBody.formParam append extra '&' at the end of last request parameter #85

Problem definition:
RequestBody.BaseBody.formParam() now always appends '&' at the end of every name-value pair of form parameters. However, there should be no '&' at the last name value pair (after call "back()"). 

Fix contains:
droping out the extra '&' when calling back() method. No other logic is changed

@dmarkov please init review. Thanks.

### CODE REVIEW

**Comment by dmarkov** [comment]
@yamstranger Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@dmzaytsev could you please review this PR

**Comment by dmzaytsev** [comment]
@YamStranger all builds failed, let's fix it

**Comment by dmzaytsev** [comment]
@YamStranger I see no tests here. You have to create a test first to reproduce the issue

**Comment by YamStranger** [comment]
@dmzaytsev Sounds like new issue for creating tests, like here https://github.com/jcabi/jcabi-aether/issues/61. @dmarkov, do you agree?

**Comment by dmzaytsev** [comment]
@YamStranger I think creating a puzzle is not an applicable way here. Creating a test is the first thing you should have done. Just create a new method in `BaseRequestTest` that reproduce the issue from the original ticket.  And only after that it will be possible to correct the error.
Right now I see the issue isn't resolved in this PR

**Comment by dmzaytsev** [comment]
@YamStranger ping

**Comment by YamStranger** [comment]
@dmzaytsev working

**Comment by YamStranger** [comment]
@dmzaytsev Problem not in my test, I reported new issue #104. 
Results : 
 
Failed tests:  
  TrustedWireITCase.ignoresPkixErrors:51 HTTP response status is not equal to 404:
500 Internal Server Error [https://api.travis-ci.org/test]
Status: 500 Internal Server Error
Date: Thu, 23 Jul 2015 09:30:48 GMT
Via: 1.1 vegur
Content-Type: application/json
Connection: close
Server: Cowboy
 
{"error":"Travis encountered an error, sorry :("}
Expected: HTTP response with status 404
     but: was <500 Internal Server Error [https://api.travis-ci.org/test]
Status: 500 Internal Server Error
Date: Thu, 23 Jul 2015 09:30:48 GMT
Via: 1.1 vegur
Content-Type: application/json
Connection: close
Server: Cowboy
 
{"error":"Travis encountered an error, sorry :("}> 
 
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0

**Comment by dmzaytsev** [comment]
@YamStranger I guess it was a temporary issue with api.travis-ci.org
just push the changes as I mentioned above https://github.com/jcabi/jcabi-http/pull/103#issuecomment-124070701

**Comment by YamStranger** [comment]
@dmarkov  I committed "always successful" test method to show that it was not "temporary issue with api.travis-ci.org". Below you can find same error and same problem. So this issue blocked by #104.

Here is copied log:

Results :
Failed tests: 
  TrustedWireITCase.ignoresPkixErrors:51 HTTP response status is not equal to 404:
500 Internal Server Error [https://api.travis-ci.org/test]
Status: 500 Internal Server Error
Date: Thu, 23 Jul 2015 09:31:42 GMT
Via: 1.1 vegur
Content-Type: application/json
Connection: close
Server: Cowboy
{"error":"Travis encountered an error, sorry :("}
Expected: HTTP response with status 404
     but: was <500 Internal Server Error [https://api.travis-ci.org/test]
Status: 500 Internal Server Error
Date: Thu, 23 Jul 2015 09:31:42 GMT
Via: 1.1 vegur
Content-Type: application/json
Connection: close
Server: Cowboy
{"error":"Travis encountered an error, sorry :("}>
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0

**Comment by alxn** [comment]
@yegor256 seemingly my PR fixes the same issue - in a different way.

**Comment by yegor256** [comment]
@alxn which PR you're talking about? I can't find it...

**Comment by alxn** [comment]
@yegor256 PR #107 ? (the only other open PR for this project).

**Comment by yegor256** [comment]
@alxn right, my bad... let's try to merge it again, I fixed some integration tests

**Comment by dmzaytsev** [comment]
@yegor256 seems we have two PRs for one issue...
what shall we to do with this PR?

**Comment by yegor256** [comment]
@dmzaytsev let's wait for #107 to get merged, then will discuss

**Comment by longtimeago** [comment]
@dmzaytsev we can proceed here I guess

**Comment by dmzaytsev** [comment]
@yegor256 PR #107 merged
I guess @YamStranger should close this PR, isn't?

> yegor256 commented 10 days ago
> @dmzaytsev let's wait for #107 to get merged, then will discuss

**Comment by dmzaytsev** [comment]
@YamStranger please close this PR

**Comment by dmzaytsev** [comment]
@YamStranger ping

**Comment by dmarkov** [comment]
@dmzaytsev Much appreciated! **24 mins** was added to your account, payment ID `65252325`, time spent is 1268 hours and 53 mins

you're getting extra minutes here (c=9)

+24 added to your rating, at the moment it is: [+1162](http://www.netbout.com/b/35166?open=rating)

**Pull request closed without merging**
