### PR TITLE
For #126: Upgrade Grizzly to 2.4.4

### PR DESCRIPTION
**Pull request by andreoss**
This is for #126 

- Upgrade
- Add puzzle for removing port reservation

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#205](https://github.com/jcabi/jcabi-http/issues/205); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by andreoss** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#205` is not assigned, can't get performer

**Pull request merged**
