### PR TITLE
#113 MkQuery can return binary body

### PR DESCRIPTION
**Pull request by longtimeago**
#113 `MkQuery` can return binary body

### CODE REVIEW

**Comment by longtimeago** [comment]
@dmarkov here is the PR, find someone to review it

**Comment by dmarkov** [comment]
@longtimeago Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@dmzaytsev could you please review this PR

**Comment by dmzaytsev** [comment]
@longtimeago looks good, thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by longtimeago** [comment]
@yegor256 could you please finish here?

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by longtimeago** [comment]
@yegor256 could you please release a new version?

**Comment by dmarkov** [comment]
@dmzaytsev **17 mins** sent to your balance (ID `66771293`), many thanks! It took 72 hours and 12 mins.... extra minutes for review comments (c=2)... +17 to your rating, your total score is [+1269](http://www.netbout.com/b/35166?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
