### PR TITLE
#96 MkContainer extends Closeable

### PR DESCRIPTION
**Pull request by longtimeago**
#96 `MkContainer` extends `Closeable` now
Compilation source and target versions were risen up to 1.7 (as according to README we support Java 7 and higher)

### CODE REVIEW

**Comment by dmarkov** [comment]
@longtimeago Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@pinaf could you please review this pull request

**Comment by pinaf** [comment]
@longtimeago beautiful

**Comment by pinaf** [comment]
@rultor merge

**Comment by longtimeago** [comment]
@pinaf thanks :)

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by longtimeago** [comment]
@rultor please, try to merge again

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@pinaf Much appreciated! **17 mins** was added to your account, payment ID `AP-93B21680KN513644L`, time spent is 25 hours and 36 mins... extra minutes for review comments (c=2)... +17 added to your rating, at the moment it is: [+4274](http://www.netbout.com/b/35128?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
