### PR TITLE
Fixed Javadocs

### LINKED ISSUE #173: Maven javadoc plugin complains
It [started](https://github.com/jcabi/jcabi-http/issues/170#issuecomment-356031132) complaining about certain annotations found in the javadocs. We have to fix this in order to release the new version.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #173 
Changed some javadocs in order for the maven-javadoc-plugin to stop complaining about their format.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#174](https://github.com/jcabi/jcabi-http/issues/174) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@yegor256 Can we merge this and release? I really need that public BaseRequest as well (https://github.com/jcabi/jcabi-http/issues/170) :)

**Comment by amihaiemil** [comment]
@yegor256 well, I see it also complains about checkstyle and todo annotations -- these have to be excluded in the plugin's declaration, which I think is inte jcabi parent

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#174` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#174](https://github.com/jcabi/jcabi-http/issues/174) is now out of scope

**Pull request merged**
