### PR TITLE
#60 - bounded Response as return type

### PR DESCRIPTION
**Pull request by RomanKisilenko**
Committed fixes for #60

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by dmarkov** [comment]
@carlosmiranda please review, thanks

**Comment by carlosmiranda** [comment]
@RomanKisilenko Thanks for the pull request.

**Comment by carlosmiranda** [comment]
@rultor Merge please

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@carlosmiranda Much obliged! I've added **19 mins** to your account in payment "50565641"... added +19 to your rating, now it is equal to [+1633](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
