### PR TITLE
For #185: Fix appveyor build

### PR DESCRIPTION
**Pull request by andreoss**
- Switch to jdk 8
- Use pre-installed maven which is newer: https://www.appveyor.com/docs/windows-images-software/
- Add xcop

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by andreoss** [comment]
Built with new config: https://ci.appveyor.com/project/andreoss/jcabi-http/builds/33798140

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#197](https://github.com/jcabi/jcabi-http/issues/197); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@andreoss thanks!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#197` is not assigned, can't get performer

**Comment by andreoss** [comment]
@yegor256 It didn't work. Can you check settings in the Appveyor console, maybe you need to change build image to most recent? For me, it works with defaults https://ci.appveyor.com/project/andreoss/jcabi-http

**Pull request merged**
