### PR TITLE
Add automatic version detection to Javadoc badge

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 Thank you, I have added **16 mins** to your account in payment/transaction "`000-220d3dc5`", time consumed: 19 hours and 6 mins. you're getting extra minutes here (c=1). +16 to your rating, your total score is [+4207](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
