### PR TITLE
Simple YmlResponse

### PR DESCRIPTION
**Pull request by Pastor**

### CODE REVIEW

**Comment by Pastor** [comment]
I so sorry for my many commits, but i tried create much better :)

**Comment by dmarkov** [comment]
@pastor Many thanks, I will find someone to review it before we merge

**Comment by yegor256** [comment]
@Pastor I don't think it's mergeable. Did you try to run `mvn clean install -Pqulice`?

**Comment by andreoss** [comment]
@Pastor 
Closing because the source branch was apparently removed. 
Please open a bug for YAML support.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#155` is not assigned, can't get performer

**Pull request closed without merging**
