### PR TITLE
Issue #160: fixed back() method losing connect and read timeouts.

### PR DESCRIPTION
**Pull request by ivanov-d**
Finishing https://github.com/jcabi/jcabi-http/pull/149

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#191` is not assigned, can't get performer

**Comment by 0crat** [comment]
Pull request [#191](https://github.com/jcabi/jcabi-http/issues/191) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#191` is not assigned, can't get performer

**Pull request merged**
