### PR TITLE
Unittest to prove timout call order matters

### PR DESCRIPTION
**Pull request by jakob-o**

### CODE REVIEW

**Comment by yegor256** [comment]
@jakob-o many thanks for the pull request, it looks good. However, you have to run `mvn clean install -Pqulice` -- there will be some static analysis problems. Please, fix it and let me know. I will try to merge.

**Comment by jakob-o** [comment]
@yegor256 Done. Just a note the qulice compliance is really strict and kind of a hurdle...

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@jakob-o Thanks for your pull request, let me find someone who can review it

**Comment by jakob-o** [comment]
Btw. since now there is a unit test (which I also could extend a little) it would be easy to include the fix itself in the PR (if my initial analysis is correct).

**Comment by jakob-o** [comment]
Ping @yegor256

**Comment by jakob-o** [comment]
Ping @yegor256

**Comment by jakob-o** [comment]
@yegor256 I extended the tests and added the actual fix. Again the code analysis checks are ridiculously strict, it took me approximately 10 times the time to make the test comply with the rules (requiring checkstyle exceptions to allow properly formatted PMD exceptions...) than it took me analyzing the problem, writing tests and fixing the issue. Not sure if this is actually a QA benefit.

PS: Failing build seems to be due to infrastructure issues, not due to code changes.

**Comment by jakob-o** [comment]
Hi @yegor256,

I saw you merged my other PR. Would you mind kicking this off, too?

Regards

Jakob

**Comment by yegor256** [comment]
@rultor merge

**Comment by jakob-o** [comment]
@yegor256 Thanks

**Pull request merged**
