### PR TITLE
Implementing formParam for multipart with tests

### PR DESCRIPTION
**Pull request by piotrkot**
Sorry for the big PR. I just miss this basic functionality.
The code was tested with takes (1.17) (`RqMtSmart`)

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by piotrkot** [comment]
@yegor256 Could you please help me with this one? There seem to be a problem with CI setup.

**Comment by 0crat** [comment]
Job [#184](https://github.com/jcabi/jcabi-http/issues/184) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#184](https://github.com/jcabi/jcabi-http/issues/184); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#184](https://github.com/jcabi/jcabi-http/issues/184); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#184](https://github.com/jcabi/jcabi-http/issues/184); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#184](https://github.com/jcabi/jcabi-http/issues/184); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#184](https://github.com/jcabi/jcabi-http/issues/184); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by piotrkot** [comment]
@yegor256 Is there a way make a progress here? How can I help?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#184](https://github.com/jcabi/jcabi-http/issues/184); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#184](https://github.com/jcabi/jcabi-http/issues/184) is now out of scope

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#184` is not assigned, can't get performer

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by piotrkot** [comment]
@yegor256 Could you please make a release with this fix?

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.0`

**Comment by yegor256** [comment]
@rultor release, tag is `1.18.0`

**Comment by piotrkot** [comment]
@yegor256 Releasing tag 1.18.0 failed. Can you please give me a hint to help me resolve it?

**Comment by yegor256** [comment]
@piotrkot yes, you can help. Try to run `mvn clean site` and you will see the problems. To fix them you should move checkstyle annotations from JavaDoc to normal commits. For example:

```
/**
 * @checkstyle LineLength (1 line)
 */
```

Should become:

```
// @checkstyle LineLength (1 line)
```

Can you do this?

**Comment by piotrkot** [comment]
@yegor256 Sure, I'll try.

**Comment by piotrkot** [comment]
@yegor256 I fixed all the checkstyle annotations listed in failed build.
Unfortunately, running `mvn clean site` locally doesn't show the checkstyle problems.

I think this is a serious problem I cannot locally see the issues reported by AppVeyor, Travis, Rultor during remote builds and releases. This needlessly slows down the process.

**Pull request merged**
